version: '3.8'
services:
    app:
        image: app-back
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "9001:9001"
        depends_on:
        - db
        links:
        - db:5432
    db:
        image: postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: medtec
        ports:
        - "5432:5432"


